from __future__ import annotations


SAMPLE_MOVIES_LIBRARY_ID = "sample-library-movies"
SAMPLE_SERIES_LIBRARY_ID = "sample-library-series"

FALLBACK_MEDIA = [
    {
        "id": "sample-dune-part-two",
        "title": "Dune: Part Two",
        "year": "2024",
        "type": "Movie",
        "genres": ["科幻", "史诗"],
        "rating": "8.4",
        "posterUrl": "https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
        "overview": "沙丘的下一段旅程。示例数据用于 Emby 未配置时验证首页视觉。",
        "libraryId": SAMPLE_MOVIES_LIBRARY_ID,
        "libraryName": "电影库",
    },
    {
        "id": "sample-blade-runner-2049",
        "title": "Blade Runner 2049",
        "year": "2017",
        "type": "Movie",
        "genres": ["科幻", "悬疑"],
        "rating": "8.0",
        "posterUrl": "https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
        "overview": "霓虹、雨夜与复制人的记忆。用来校验暗场背景和海报光影。",
        "libraryId": SAMPLE_MOVIES_LIBRARY_ID,
        "libraryName": "电影库",
    },
    {
        "id": "sample-interstellar",
        "title": "Interstellar",
        "year": "2014",
        "type": "Movie",
        "genres": ["科幻", "冒险"],
        "rating": "8.7",
        "posterUrl": "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
        "overview": "穿过虫洞寻找新的家园。适合作为大屏标题和粒子背景测试素材。",
        "libraryId": SAMPLE_MOVIES_LIBRARY_ID,
        "libraryName": "电影库",
    },
    {
        "id": "sample-arrival",
        "title": "Arrival",
        "year": "2016",
        "type": "Movie",
        "genres": ["科幻", "剧情"],
        "rating": "7.9",
        "posterUrl": "https://image.tmdb.org/t/p/w780/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/yIZ1xendyqKvY3FGeeUYUd5X9Mm.jpg",
        "overview": "关于语言、时间和选择的柔性科幻。",
        "libraryId": SAMPLE_MOVIES_LIBRARY_ID,
        "libraryName": "电影库",
    },
    {
        "id": "sample-oppenheimer",
        "title": "Oppenheimer",
        "year": "2023",
        "type": "Movie",
        "genres": ["传记", "历史"],
        "rating": "8.1",
        "posterUrl": "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
        "overview": "强对比光影素材，用来验证标题可读性和暗化遮罩。",
        "libraryId": SAMPLE_MOVIES_LIBRARY_ID,
        "libraryName": "电影库",
    },
    {
        "id": "sample-the-batman",
        "title": "The Batman",
        "year": "2022",
        "type": "Movie",
        "genres": ["犯罪", "动作"],
        "rating": "7.7",
        "posterUrl": "https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhqg.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
        "overview": "低照度和红色强调色，用来检查首页色彩弹性。",
        "libraryId": SAMPLE_MOVIES_LIBRARY_ID,
        "libraryName": "电影库",
    },
    {
        "id": "sample-inception",
        "title": "Inception",
        "year": "2010",
        "type": "Movie",
        "genres": ["动作", "悬疑"],
        "rating": "8.4",
        "posterUrl": "https://image.tmdb.org/t/p/w780/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
        "overview": "梦境折叠，适合验证舞台旋转和背景层次。",
        "libraryId": SAMPLE_MOVIES_LIBRARY_ID,
        "libraryName": "电影库",
    },
    {
        "id": "sample-mad-max-fury-road",
        "title": "Mad Max: Fury Road",
        "year": "2015",
        "type": "Movie",
        "genres": ["动作", "冒险"],
        "rating": "8.1",
        "posterUrl": "https://image.tmdb.org/t/p/w780/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/phszHPFVhPHhMZgo0fWTKBDQsJA.jpg",
        "overview": "高饱和场景，用来校验背景滤镜和文字压暗层。",
        "libraryId": SAMPLE_MOVIES_LIBRARY_ID,
        "libraryName": "电影库",
    },
    {
        "id": "sample-severance",
        "title": "Severance",
        "year": "2022",
        "type": "Series",
        "genres": ["剧集", "悬疑"],
        "rating": "8.6",
        "posterUrl": "https://image.tmdb.org/t/p/w780/lFf6LLrQjYldcZItzOkGmMMigP7.jpg",
        "backdropUrl": "https://image.tmdb.org/t/p/original/5O0Y4ZkUwM5zFysTcnXQnV82hyU.jpg",
        "overview": "剧集类型示例，用来验证 Movie / Series 混排。",
        "libraryId": SAMPLE_SERIES_LIBRARY_ID,
        "libraryName": "剧集库",
    },
]

FALLBACK_LIBRARIES = [
    {
        "id": SAMPLE_MOVIES_LIBRARY_ID,
        "name": "电影库",
        "collectionType": "movies",
        "posterUrl": FALLBACK_MEDIA[0]["posterUrl"],
        "backdropUrl": FALLBACK_MEDIA[0]["backdropUrl"],
        "itemCount": 8,
    },
    {
        "id": SAMPLE_SERIES_LIBRARY_ID,
        "name": "剧集库",
        "collectionType": "tvshows",
        "posterUrl": FALLBACK_MEDIA[8]["posterUrl"],
        "backdropUrl": FALLBACK_MEDIA[8]["backdropUrl"],
        "itemCount": 1,
    },
]
